version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: leovagas-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: leovagasdb
      MYSQL_USER: leovagasuser
      MYSQL_PASSWORD: leovagaspass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data: 